### ISSUE TITLE
Falcon CTRE library error :)

### ISSUE THREAD

**Issue by KilroyWasHere-cs-j** [frc5687/2021-robot#14]
Falcon libraries aren't working properly. Not sure on the cause of the library error still working on a solution.

**Comment by greenermoose** [comment]
Please describe error and what triggers it!

**Comment by KilroyWasHere-cs-j** [comment]
Trying a library reinstall Phoenix.

**Comment by KilroyWasHere-cs-j** [comment]
<img width="645" alt="NullPointer" src="https://user-images.githubusercontent.com/59028838/134583946-58129f67-5391-4a7a-99ad-2b7b03050cab.PNG">

**Comment by KilroyWasHere-cs-j** [comment]
Looks like it's a null pointer error. Maybe can be fixed when connected to the robot.

**Comment by KilroyWasHere-cs-j** [comment]
Don't call the limelight in Robot.java
Who'd a thought? :)
